version: '3.8'  # Pode manter ou remover esta linha

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: ecommerce
    ports:
      - "3306:3306"

  products:
    build: ./node-api  # Certifique-se que esta pasta existe
    ports:
      - "3001:3001"

  orders:
    build: ./python-api  # Alterado para apontar para python-api
    ports:
      - "3002:3002"
    environment:
      - REDIS_HOST=redis
      - PRODUCTS_API_URL=http://products:3001/products
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=example
      - MYSQL_DB=ecommerce
    depends_on:
      - db
      - redis
      - products
  payments:
    build: ./php-api
    ports:
      - "3003:80"
    depends_on:
      - orders